### PR TITLE
Change module name to influxdata/sarama

### PR DESCRIPTION
**Pull request by andig**
Fix follow-on issue of forking sarama from https://github.com/influxdata/telegraf/pull/6349#issuecomment-548450552

### CODE REVIEW

**Comment by glinton** [comment]
You'll likely want to edit this pr to merge into the branch `without-zstd` instead of master however

**Comment by andig** [comment]
> You'll likely want to edit this pr to merge into the branch without-zstd instead of master however

fixed, thanks for the quick reply

**Comment by andig** [comment]
Confirmed working, thank you!

**Pull request merged**
